"""Write-gate plumbing: shared secret + generated Claude hook artifacts.

The Claude branch of the write-gate runs a ``PreToolUse`` hook that POSTs the
tool call to the connector approval endpoint and blocks on the response.
This module generates that hook script and the ``--settings`` file Claude is
launched with, and manages the shared secret the endpoint authenticates with.

The Codex branch needs none of this — it relies on Codex's native
``untrusted`` approval prompts, intercepted from the pane by the connector.
"""

from __future__ import annotations

import json
import logging
import os
import secrets
import sys
from pathlib import Path
from typing import Any

from ..config import config
from ..utils import codexbot_dir

logger = logging.getLogger(__name__)

HOOK_TIMEOUT_SECONDS = 600  # matches Claude's command-hook ceiling (10 min)
_SECRET_FILENAME = "approval_secret"
_HOOK_SCRIPT_NAME = "approval_hook.py"
_CLAUDE_SETTINGS_NAME = "claude_hook_settings.json"
# Tools whose calls are routed to the endpoint; reads (Read/Grep/Glob) are
# deliberately excluded so they never incur hook overhead.
_HOOK_MATCHER = "Edit|Write|MultiEdit|NotebookEdit|Bash"


def connectors_state_dir() -> Path:
    path = codexbot_dir() / "connectors"
    path.mkdir(parents=True, exist_ok=True)
    return path


def approval_secret() -> str:
    """Return the endpoint shared secret, generating it once at 0600."""
    path = connectors_state_dir() / _SECRET_FILENAME
    try:
        existing = path.read_text(encoding="utf-8").strip()
        if existing:
            return existing
    except OSError:
        pass
    token = secrets.token_urlsafe(32)
    path.write_text(token, encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass
    return token


def approval_endpoint_url() -> str:
    return f"http://127.0.0.1:{config.web_ui_port}/api/connectors/approve-tool"


def _hook_script_source(url: str, secret: str) -> str:
    # Stdlib-only so it runs under any python3. Fail-open on transport error
    # to avoid bricking the agent when the connector process is unreachable.
    return f'''#!/usr/bin/env python3
"""Generated by codexbot connectors — do not edit. PreToolUse write-gate."""
import json
import sys
import urllib.request

URL = {url!r}
SECRET = {secret!r}
TIMEOUT = {HOOK_TIMEOUT_SECONDS}


def _allow():
    print(json.dumps({{"hookSpecificOutput": {{
        "hookEventName": "PreToolUse", "permissionDecision": "allow"}}}}))
    sys.exit(0)


def main():
    raw = sys.stdin.read()
    try:
        payload = json.loads(raw) if raw.strip() else {{}}
    except Exception:
        _allow()
    req = urllib.request.Request(
        URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={{"Content-Type": "application/json", "X-Connector-Secret": SECRET}},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            sys.stdout.write(resp.read().decode("utf-8"))
    except Exception as exc:
        sys.stderr.write("codexbot approval unreachable: %s\\n" % exc)
        _allow()


if __name__ == "__main__":
    main()
'''


def _claude_settings_source(hook_command: str) -> str:
    import json

    return json.dumps(
        {
            "hooks": {
                "PreToolUse": [
                    {
                        "matcher": _HOOK_MATCHER,
                        "hooks": [
                            {
                                "type": "command",
                                "command": hook_command,
                                "timeout": HOOK_TIMEOUT_SECONDS,
                            }
                        ],
                    }
                ]
            }
        },
        indent=2,
    )


def ensure_claude_hook_settings() -> str:
    """Materialize the hook script + settings file; return the settings path.

    Regenerates on every call so a changed port/secret is always reflected.
    """
    state = connectors_state_dir()
    secret = approval_secret()
    url = approval_endpoint_url()

    script_path = state / _HOOK_SCRIPT_NAME
    script_path.write_text(_hook_script_source(url, secret), encoding="utf-8")
    try:
        os.chmod(script_path, 0o700)
    except OSError:
        pass

    python = sys.executable or "python3"
    hook_command = f"{python} {script_path}"
    settings_path = state / _CLAUDE_SETTINGS_NAME
    settings_path.write_text(_claude_settings_source(hook_command), encoding="utf-8")

    return str(settings_path)


# --- shared write-gate decision (used by web + headless approval servers) ---


def _allow() -> dict[str, Any]:
    return {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "allow",
        }
    }


def _deny(reason: str) -> dict[str, Any]:
    return {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }


def _describe_tool_call(tool_name: str, tool_input: Any) -> str:
    if not isinstance(tool_input, dict):
        return tool_name
    if "command" in tool_input:
        return str(tool_input.get("command") or "")
    path = tool_input.get("file_path") or tool_input.get("path") or ""
    if path:
        return f"{tool_name}: {path}"
    try:
        return f"{tool_name} {json.dumps(tool_input, ensure_ascii=False)[:500]}"
    except (TypeError, ValueError):
        return tool_name


async def decide_tool_call(payload: dict[str, Any]) -> dict[str, Any]:
    """Decide a PreToolUse hook call → allow/deny JSON.

    Reads pass immediately; writes are routed to the owning connector, which
    blocks on a human decision (Slack Approve/Deny). Shared by the web-UI
    endpoint and the headless approval server.
    """
    from . import bridge, store
    from .classifier import classify_action
    from .manager import connector_manager

    tool_name = str(payload.get("tool_name") or "")
    tool_input = payload.get("tool_input") or {}
    session_id = str(payload.get("session_id") or "")

    if classify_action(tool_name, tool_input) == "read":
        return _allow()

    window_id = bridge.window_for_session(session_id)
    if not window_id:
        return _allow()  # not a connector-managed session
    mapping = store.find_mapping_by_window(window_id)
    if mapping is None:
        return _allow()
    connector = connector_manager.get_connector(mapping.connector_id)
    if connector is None:
        return _allow()

    extra_reads = connector.config.get("extra_read_commands") or []
    if isinstance(extra_reads, list) and (
        classify_action(tool_name, tool_input, tuple(str(x) for x in extra_reads))
        == "read"
    ):
        return _allow()

    detail = _describe_tool_call(tool_name, tool_input)
    approved = await connector.request_write_approval(
        window_id, f"{tool_name} requires approval", detail
    )
    return _allow() if approved else _deny("Denied by reviewer")


__all__ = [
    "HOOK_TIMEOUT_SECONDS",
    "approval_endpoint_url",
    "approval_secret",
    "connectors_state_dir",
    "decide_tool_call",
    "ensure_claude_hook_settings",
]
