"""Write-gate plumbing: shared secret + generated Claude hook artifacts.

The Claude branch of the write-gate runs a ``PreToolUse`` hook that POSTs the
tool call to the connector approval endpoint and blocks on the response.
This module generates that hook script and the ``--settings`` file Claude is
launched with, and manages the shared secret the endpoint authenticates with.

The Codex branch needs none of this — it relies on Codex's native
``untrusted`` approval prompts, intercepted from the pane by the connector.
"""

from __future__ import annotations

import logging
import os
import secrets
import sys
from pathlib import Path

from ..config import config
from ..utils import codexbot_dir

logger = logging.getLogger(__name__)

HOOK_TIMEOUT_SECONDS = 600  # matches Claude's command-hook ceiling (10 min)
_SECRET_FILENAME = "approval_secret"
_HOOK_SCRIPT_NAME = "approval_hook.py"
_CLAUDE_SETTINGS_NAME = "claude_hook_settings.json"
# Tools whose calls are routed to the endpoint; reads (Read/Grep/Glob) are
# deliberately excluded so they never incur hook overhead.
_HOOK_MATCHER = "Edit|Write|MultiEdit|NotebookEdit|Bash"


def connectors_state_dir() -> Path:
    path = codexbot_dir() / "connectors"
    path.mkdir(parents=True, exist_ok=True)
    return path


def approval_secret() -> str:
    """Return the endpoint shared secret, generating it once at 0600."""
    path = connectors_state_dir() / _SECRET_FILENAME
    try:
        existing = path.read_text(encoding="utf-8").strip()
        if existing:
            return existing
    except OSError:
        pass
    token = secrets.token_urlsafe(32)
    path.write_text(token, encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass
    return token


def approval_endpoint_url() -> str:
    return f"http://127.0.0.1:{config.web_ui_port}/api/connectors/approve-tool"


def _hook_script_source(url: str, secret: str) -> str:
    # Stdlib-only so it runs under any python3. Fail-open on transport error
    # to avoid bricking the agent when the connector process is unreachable.
    return f'''#!/usr/bin/env python3
"""Generated by codexbot connectors — do not edit. PreToolUse write-gate."""
import json
import sys
import urllib.request

URL = {url!r}
SECRET = {secret!r}
TIMEOUT = {HOOK_TIMEOUT_SECONDS}


def _allow():
    print(json.dumps({{"hookSpecificOutput": {{
        "hookEventName": "PreToolUse", "permissionDecision": "allow"}}}}))
    sys.exit(0)


def main():
    raw = sys.stdin.read()
    try:
        payload = json.loads(raw) if raw.strip() else {{}}
    except Exception:
        _allow()
    req = urllib.request.Request(
        URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={{"Content-Type": "application/json", "X-Connector-Secret": SECRET}},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            sys.stdout.write(resp.read().decode("utf-8"))
    except Exception as exc:
        sys.stderr.write("codexbot approval unreachable: %s\\n" % exc)
        _allow()


if __name__ == "__main__":
    main()
'''


def _claude_settings_source(hook_command: str) -> str:
    import json

    return json.dumps(
        {
            "hooks": {
                "PreToolUse": [
                    {
                        "matcher": _HOOK_MATCHER,
                        "hooks": [
                            {
                                "type": "command",
                                "command": hook_command,
                                "timeout": HOOK_TIMEOUT_SECONDS,
                            }
                        ],
                    }
                ]
            }
        },
        indent=2,
    )


def ensure_claude_hook_settings() -> str:
    """Materialize the hook script + settings file; return the settings path.

    Regenerates on every call so a changed port/secret is always reflected.
    """
    state = connectors_state_dir()
    secret = approval_secret()
    url = approval_endpoint_url()

    script_path = state / _HOOK_SCRIPT_NAME
    script_path.write_text(_hook_script_source(url, secret), encoding="utf-8")
    try:
        os.chmod(script_path, 0o700)
    except OSError:
        pass

    python = sys.executable or "python3"
    hook_command = f"{python} {script_path}"
    settings_path = state / _CLAUDE_SETTINGS_NAME
    settings_path.write_text(_claude_settings_source(hook_command), encoding="utf-8")

    return str(settings_path)


__all__ = [
    "HOOK_TIMEOUT_SECONDS",
    "approval_endpoint_url",
    "approval_secret",
    "connectors_state_dir",
    "ensure_claude_hook_settings",
]
