"""Claude Code lifecycle hooks: authoritative session binding and prompt pokes.

Every Claude window codexbot launches loads a ``--settings`` file that wires
two hooks to a tiny stdlib script. The script forwards the hook payload plus
the pane it runs in (``$TMUX_PANE`` / ``$TMUX``, inherited from the tmux pane)
to ``POST /api/hooks/claude``:

* ``SessionStart`` (startup / resume / clear / compact) carries the new
  ``session_id``, so a window is rebound the moment Claude mints an id instead
  of waiting for the next ``ps`` + ``~/.claude/sessions`` probe.
* ``Notification`` fires when Claude waits on the user (permission, plan
  approval, AskUserQuestion); it triggers an immediate pane check so the
  interactive prompt reaches the web UI without waiting for the next poll.

The script never blocks Claude: it has a short timeout, swallows every error
and prints nothing.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any

from .config import config
from .utils import codexbot_dir

if TYPE_CHECKING:
    from .web.events import EventBus
    from .web.interactive_monitor import InteractivePromptMonitor

logger = logging.getLogger(__name__)

HOOK_EVENTS = ("SessionStart", "Notification")
HOOK_TIMEOUT_SECONDS = 5
_SCRIPT_NAME = "claude_event_hook.py"
_SETTINGS_NAME = "claude_event_hooks.json"
_TMUX_TIMEOUT_SECONDS = 3.0


def hook_endpoint_url() -> str:
    return f"http://127.0.0.1:{config.web_ui_port}/api/hooks/claude"


def _script_source(url: str, secret: str) -> str:
    return f'''#!/usr/bin/env python3
"""Generated by codexbot — do not edit. Forwards Claude hook events."""
import json
import os
import sys
import urllib.request

URL = {url!r}
SECRET = {secret!r}


def main():
    try:
        payload = json.loads(sys.stdin.read() or "{{}}")
        payload["tmux_pane"] = os.environ.get("TMUX_PANE", "")
        payload["tmux"] = os.environ.get("TMUX", "")
        req = urllib.request.Request(
            URL,
            data=json.dumps(payload).encode("utf-8"),
            headers={{"Content-Type": "application/json", "X-Hook-Secret": SECRET}},
            method="POST",
        )
        urllib.request.urlopen(req, timeout=2).close()
    except Exception:
        pass


if __name__ == "__main__":
    main()
'''


def hook_command() -> str:
    """Materialize the forwarding script; return the command that runs it."""
    from .connectors.approval import approval_secret

    directory = codexbot_dir() / "claude-hooks"
    directory.mkdir(parents=True, exist_ok=True)
    script = directory / _SCRIPT_NAME
    script.write_text(
        _script_source(hook_endpoint_url(), approval_secret()), encoding="utf-8"
    )
    try:
        os.chmod(script, 0o700)
    except OSError:
        pass
    return f"{sys.executable or 'python3'} {script}"


def event_hook_settings(command: str) -> dict[str, list[dict[str, Any]]]:
    """The ``hooks`` settings block that routes HOOK_EVENTS to ``command``."""
    return {
        event: [
            {
                "hooks": [
                    {
                        "type": "command",
                        "command": command,
                        "timeout": HOOK_TIMEOUT_SECONDS,
                    }
                ]
            }
        ]
        for event in HOOK_EVENTS
    }


def ensure_event_hook_settings() -> str:
    """Write the settings file Claude windows are launched with; return its path.

    Regenerated on every launch so a changed port or secret is picked up.
    """
    directory = codexbot_dir() / "claude-hooks"
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / _SETTINGS_NAME
    path.write_text(
        json.dumps({"hooks": event_hook_settings(hook_command())}, indent=2),
        encoding="utf-8",
    )
    return str(path)


async def window_for_pane(tmux_env: str, pane_id: str) -> str | None:
    """Resolve a hook's ``$TMUX_PANE`` to a codexbot window id.

    ``$TMUX`` is ``<socket>,<pid>,<session>``; asking that exact server keeps
    panes of an unrelated tmux server from being confused with ours.
    """
    if not pane_id.startswith("%"):
        return None
    socket = tmux_env.split(",", 1)[0]
    cmd = ["tmux"]
    if socket:
        cmd += ["-S", socket]
    cmd += ["display-message", "-p", "-t", pane_id, "#{session_name}\t#{window_id}"]
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.DEVNULL,
        )
        out, _ = await asyncio.wait_for(proc.communicate(), _TMUX_TIMEOUT_SECONDS)
    except (OSError, asyncio.TimeoutError) as e:
        logger.debug("tmux pane lookup failed for %s: %s", pane_id, e)
        return None
    session_name, _, window_id = out.decode().strip().partition("\t")
    if session_name != config.tmux_session_name or not window_id.startswith("@"):
        return None
    return window_id


async def handle_hook_event(
    payload: dict[str, Any],
    *,
    bus: "EventBus | None" = None,
    interactive_monitor: "InteractivePromptMonitor | None" = None,
) -> None:
    from .session import session_manager

    event = payload.get("hook_event_name")
    if event not in HOOK_EVENTS:
        return
    window_id = await window_for_pane(
        str(payload.get("tmux") or ""), str(payload.get("tmux_pane") or "")
    )
    if window_id is None:
        return

    if event == "SessionStart":
        session_id = payload.get("session_id")
        if not isinstance(session_id, str) or not session_id:
            return
        cwd = payload.get("cwd")
        rebound = await session_manager.bind_claude_session_from_hook(
            window_id,
            session_id,
            cwd=cwd if isinstance(cwd, str) else None,
            transcript_path=_path_or_none(payload.get("transcript_path")),
        )
        if rebound and bus is not None:
            await bus.publish_sessions_changed()
    elif event == "Notification" and interactive_monitor is not None:
        interactive_monitor.request_check(window_id)


def _path_or_none(value: Any) -> Path | None:
    return Path(value) if isinstance(value, str) and value else None
